import java.io.File

String pipeline_name
String projectsCommonFile = readFileFromWorkspace('Jenkins/MTE_Backup_Jobs')
projectsCommonFile.eachLine {
    project_name -> createPipelineBuildJob(project_name)
}

def createPipelineBuildJob(project_name) {
    pipelineJob(project_name) {
        description ('ENM Cloud Native Backup Build pipeline ' + project_name + ' - autogenerated using JobDSL - all manual changes will be overwritten!')
        concurrentBuild(allowConcurrentBuild = true)
        logRotator {
            numToKeep(30)
        }
        parameters {
            choiceParam('deployment_mechanism',['charts','csar'],'This parameter acts as the flow controller to select the deployment mechanism either charts or csar.')
            stringParam('environment_name', '','The deployment name to run the job against')
            choiceParam('stage_area',['ci_internal','drop'],'This parameter acts as the flow controller to download charts from internal area or release area')
            stringParam('product_set_version', '','Provide clould native product set version of existing deployment on environment to take backup')
            stringParam('drop', '','provide the drop version')
            stringParam('backup_name', '','Provide BackupName')
            choiceParam('backup_scope',['DEFAULT','ROLLBACK'],'This parameter acts as the flow controller to select the scope of backup')
            labelParam('slave') {
               defaultValue("${SLAVE}")
               description('')
            }
        }

        definition {
            cpsScm {
                scm {
                    git {
                        branch('master')
                        remote {
                            credentials('lciadm100_private_key')
                            url("${GERRIT_MIRROR}/OSS/com.ericsson.oss.containerisation/eric-enm-integration-pipeline-code")
                        }
                        extensions {
                             cleanBeforeCheckout()
                        }
                    }
                }
                scriptPath("Jenkins/Jenkinsfile/JenkinsfileBackup")
                lightweight(lightweight = true)
            }
        }
    }
}
