import java.io.File

String pipeline_name
String projectsCommonFile = readFileFromWorkspace('Jenkins/MTE_Monitoring_upgrade_Jobs')
projectsCommonFile.eachLine {
    project_name -> createPipelineBuildJob(project_name)
}

def createPipelineBuildJob(project_name) {
    pipelineJob(project_name) {
        description ('ENM Cloud Native Upgrade Build pipeline ' + project_name + ' - autogenerated using JobDSL - all manual changes will be overwritten!')
        concurrentBuild(allowConcurrentBuild = true)
        logRotator {
            numToKeep(30)
        }
        parameters {
            stringParam('environment_name', '','Deployment name of cENM Cloud Deployment to be Upgraded')
            choiceParam('stage_area',['ci_internal','drop'],'This parameter acts as the flow controller to download charts from internal area or release area')
            stringParam('MONITORING_INTEGRATION_CHART_VERSION', '','Please provide the Monitoring integration chart version')
            stringParam('INTEGRATION_VALUE_VERSION', '','Please provide the Integartion values version')
            labelParam('SLAVE') {
               defaultValue("${SLAVE}")
               description('')
        }
        }

        definition {
            cpsScm {
                scm {
                    git {
                        branch('master')
                        remote {
                            credentials('lciadm100_private_key')
                            url("ssh://gerrit.ericsson.se:29418/OSS/com.ericsson.oss.containerisation/eric-enm-integration-pipeline-code")
                        }
                        extensions {
                             cleanBeforeCheckout()
                        }
                    }
                }
                scriptPath("Jenkins/Jenkinsfile/JenkinsfileUpgradeMonitoring")
                lightweight(lightweight = true)
            }
        }
    }
}
