import java.io.File

String pipeline_name
String projectsCommonFile = readFileFromWorkspace('Jenkins/Design_upgrade_Jobs')
projectsCommonFile.eachLine {
    project_name -> createPipelineBuildJob(project_name)
}

def createPipelineBuildJob(project_name) {
    pipelineJob(project_name) {
        description ('ENM Cloud Native Upgrade Build pipeline ' + project_name + ' - autogenerated using JobDSL - all manual changes will be overwritten!')
        concurrentBuild(allowConcurrentBuild = true)
        logRotator {
            numToKeep(30)
        }
        parameters {
            choiceParam('deployment_mechanism',['charts','csar'],'This parameter acts as the flow controller to select the deployment mechanism either charts or csar.')
            stringParam('environment_name', '','The deployment name to run the job against')
            choiceParam('stage_area',['ci_internal','drop'],'This parameter acts as the flow controller to download charts from internal area or release area')
            stringParam('bro_chart_version', '','Provide bro chart version to upgrade')
            stringParam('pre_deploy_chart_version', '','provide Pre Deploy integration chart version to upgrade')
            stringParam('infra_chart_version', '','provide infra integration chart version to upgrade')
            stringParam('stateless_chart_version', '','Provide stateless chart version to upgrade')
            stringParam('integration_value_version', '','Provide the integartion values version to upgrade')
            stringParam('csar_package_version', '','please provide the csar package version to upgrade')
            labelParam('slave') {
               defaultValue("${SLAVE}")
               description('')
            }
        }

        definition {
            cpsScm {
                scm {
                    git {
                        branch('master')
                        remote {
                            credentials('lciadm100_private_key')
                            url("ssh://gerrit.ericsson.se:29418/OSS/com.ericsson.oss.containerisation/eric-enm-integration-pipeline-code")
                        }
                        extensions {
                             cleanBeforeCheckout()
                        }
                    }
                }
                scriptPath("Jenkins/Jenkinsfile/JenkinsfileUpgrade")
                lightweight(lightweight = true)
            }
        }
    }
}
