
import java.io.File

buildJobNames = generateBuidJobNames()
def generateBuidJobNames() {
    def list_of_build_job_names = []
    String repos = readFileFromWorkspace('Jenkins/repo-list-for-hlc-version-update')
    repos.eachLine { String project_name ->
        project_name = project_name.split("/").last()
        list_of_build_job_names << "\"" + project_name +"_update-HLC-version"+ "\""
    }
    return list_of_build_job_names
}

def createE2EBuildPipeline() {
String e2e_steps="""SG_PROJECT_LIST = ${buildJobNames}
pipeline {
    agent { node { label 'INT_Cloud_Native' } }
    environment {
        PIPELINE_LAST_STAGE_STATUS = 'UNKNOWN'
    }
    stages {
        stage ('Get HLC Versions') {
            steps {
                script {
                    environment_list = [[\$class:'StringParameterValue', name:"CHART_VERSION", value:String.valueOf("\${CHART_VERSION}")]]
                    echo "\$environment_list"
                }
            }
        }
        stage('Updating HLC version in SG') {
            steps{
                script{
                    sh "touch hlc_failed_service_group_builds"
                    for (def service_group_build in SG_PROJECT_LIST) {
                         try{
                            stage("Build \${service_group_build}"){
                                  retry(3) {
                                    def build = build(job: "\${service_group_build}", propagate: false, wait: true, parameters: environment_list)
                                    def BuildResult = build.getResult()
                                     if (BuildResult != "SUCCESS") {
                                       error 'FAIL'
                                     }
                                 }
                              }
                            }catch (e) {
                               sh "echo \${service_group_build} >> hlc_failed_service_group_builds"
                               currentBuild.result = 'FAILURE'
                         }
                    }
                }
            }
        }
        stage('Generate Failed HLC Job File') {
            steps {
                script {
                  archiveArtifacts 'hlc_failed_service_group_builds'
                  sh "rm -rf hlc_failed_service_group_builds"
                }
            }
        }
    }
    post {
        failure {
            script {
                if (PIPELINE_LAST_STAGE_STATUS=='SUCCESS') {
                    currentBuild.rawBuild.@result = hudson.model.Result.SUCCESS
                }
            }
        }
    }
}

"""
    pipelineJob('eric-enm-e2e_update-HLC-version') {
        description ('ENM Cloud Native Build pipeline eric-enm-e2e-hlc-build - autogenerated using JobDSL - all manual changes will be overwritten!')
        parameters {
                 stringParam('CHART_VERSION')
                 blockOn(['eric-enm-e2e-build']) {
                     blockLevel('GLOBAL')
                     scanQueueFor('ALL')
             }
        }
      //concurrentBuild(allowConcurrentBuild = false)
        properties {
        disableConcurrentBuilds()
        }
        definition {
            cps {
                sandbox()
                script(e2e_steps)
            }
        }
    }
}

createE2EBuildPipeline()

listView('ENM HLC Version Update Build') {
    filterBuildQueue()
    filterExecutors()
    jobs {
        regex(/eric-enm.*_update-HLC-version/)
    }
    columns {
        status()
        weather()
        name()
        lastSuccess()
        lastFailure()
        lastDuration()
        buildButton()
    }
}
